export const AUTH_SIGN_UP='AUTH_SIGN_UP';
export const AUTH_SIGN_IN='AUTH_SIGN_IN';
export const CHANGE_NAV='CHANGE_NAV';
export const CHANGE_CURRENCY='CHANGE_CURRENCY';
export const WISHLIST_FETCH='WISHLIST_FETCH';
export const PRODUCT_FETCH='PRODUCT_FETCH';
export const SELECT_PRODUCT='SELECT_PRODUCT';
export const SELECT_WISHLIST='SELECT_WISHLIST';